install.packages('renv')
install.packages('DataExplorer')
install.packages('Rcpp')
install.packages('vip')
install.packages('rsconnect')
install.packages('paws')
install.packages('googleCloudStorageR')

renv::snapshot()
renv::restore()
renv::status()
renv::init()
Sys.getenv("GOO")