# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
    library(googleCloudStorageR)
}

gcs_auth()
b <- board_gcs("ames-r-model", prefix = NULL)
v <- vetiver_pin_read(b, "ames_rf")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
