# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}

b <- board_folder(  path="board", versioned=TRUE )
v <- vetiver_pin_read(b, "ames_rf")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
